model = dict(
    type='MapTracker',
    backbone_cfg=dict(
        type='BEVFormerBackbone',
        # /home/kuangen/anaconda3/envs/maptracker/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:306
        img_backbone=dict(
            type='ResNet',
            ),
        img_neck=dict(
            type='FPN',
            ),
        transformer=dict(
            type='PerceptionTransformer',
            encoder=dict(
                type='BEVFormerEncoder',
                transformerlayers=dict(
                    type='BEVFormerLayer',
                    attn_cfgs=[
                        dict(
                            type='TemporalSelfAttention'),
                        dict(
                            type='SpatialCrossAttention',
                            deformable_attention=dict(
                                type='MSDeformableAttention3D')
                        )
                    ],
                )
            ),
        ),
        positional_encoding=dict(
            type='LearnedPositionalEncoding',
            ),
    ),
    head_cfg=dict(
        type='MapDetectorHead',
        transformer=dict(
            type='MapTransformer',
            encoder=dict(
                type='PlaceHolderEncoder',
            ),
            decoder=dict(
                type='MapTransformerDecoder_new',
                transformerlayers=dict(
                    type='MapTransformerLayer',
                    attn_cfgs=[
                        dict(
                            type='MultiheadAttention',
                        ),
                        dict(
                            type='CustomMSDeformableAttention',
                        ),
                        dict(
                            type='MultiheadAttention',
                        ),
                    ],
                    ffn_cfgs=dict(
                        type='FFN',       
                    ),
                )
            )
        ),
        loss_cls=dict(
            type='FocalLoss',
        ),
        loss_reg=dict(
            type='LinesL1Loss',
        ),
        assigner=dict(
            type='HungarianLinesAssigner',
                cost=dict(
                    type='MapQueriesCost',
                    ),
                ),
        ),
    seg_cfg=dict(
        type='MapSegHead',
        loss_seg=dict(
            type='MaskFocalLoss',
        ),
        loss_dice=dict(
            type='MaskDiceLoss',
        )
    )
)